services:
  keygen-singbox:
    container_name: keygen
    build: keygen/.
    volumes:
      - ./data:/etc/keygen
    restart: no

  xray-vless:
    container_name: xray
    build: xray_server/.
    volumes:
      - ./data/config.json:/etc/xray/config.json
      - ./data/public_key.env:/etc/keygen/public_key.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keygen-singbox
    restart: unless-stopped
